// WARNING: This file is dynamically generated by scripts/parse-pptx.py.
// Do not edit this file directly, as it will be overwritten during compile/dev builds.

export interface SlideData {
  id: number;
  title: string;
  subtitle?: string;
  layout: 'title' | 'about' | 'services' | 'grid' | 'tools' | 'tech' | 'bullets';
  intro?: string;
  bullets?: string[];
  gridItems?: { num: string; label: string }[];
  columns?: { title: string; items: string[] }[];
}

export const portfolioSlides: SlideData[] = [
  {
    "id": 1,
    "title": "SENANITECH",
    "subtitle": "ELECTRONICS DESIGN AND MANUFACTURING SERVICE",
    "layout": "title"
  },
  {
    "id": 2,
    "title": "ABOUT US",
    "intro": "Founded in 2021, we are a dynamic Electronic Engineering and R&D Services company driven by a passion for innovation and excellence in technology. With a strong focus on delivering cutting-edge solutions, we specialize in hardware design, PCB development, and comprehensive research and development services tailored to meet the specific needs of our clients.",
    "layout": "about",
    "gridItems": [
      {
        "num": "01",
        "label": "Hardware Design"
      },
      {
        "num": "02",
        "label": "PCB Design"
      },
      {
        "num": "03",
        "label": "R&D Services"
      },
      {
        "num": "04",
        "label": "Embedded Development"
      }
    ]
  },
  {
    "id": 3,
    "title": "CONCEPT",
    "intro": null,
    "bullets": [
      "HW High Level Design",
      "HW Low Level Design",
      "Component Engineering",
      "Board Bring-Up",
      "Testing",
      "Firmware Development",
      "Driver Development",
      "HARDWARE DESIGN & FIRMWARE DEVELOPMENT",
      "PCB DESIGN & SI/PI SIMULATION",
      "ELECTRONICS MANUFACTURING SERVICE",
      "REGULATORY COMPLIANCE",
      "Concept Validation",
      "Product Specification Development",
      "System Architecture",
      "PCB Layout Design",
      "Signal / Power / Thermal Integrity Analysis",
      "High-Speed Design (HDI and ATI Boards)",
      "PCB Manufacturing ( Thru Partners)",
      "PCB Assembly",
      "Power ON Testing",
      "Box Building",
      "Cable Harness",
      "IEC 60601-1:2024",
      "ISO 13485",
      "OUR SERVICES"
    ],
    "layout": "bullets"
  },
  {
    "id": 4,
    "title": "01",
    "intro": null,
    "bullets": [
      "02",
      "03",
      "04",
      "High Dense & Complex PCB Engineering",
      "High Speed Digital Designs",
      "Analog & Mixed Signal Design",
      "RF Designs & Power Electronics",
      "DESIGN EXPERTISE"
    ],
    "layout": "bullets"
  },
  {
    "id": 5,
    "title": "PCB DESIGN",
    "intro": null,
    "bullets": [
      "01",
      "02",
      "03",
      "04",
      "BURN IN BOARDS DESIGN",
      "ATE BOARD",
      "DESIGN",
      "ICT BOARD",
      "DESIGN",
      "HIL BOARD",
      "DESIGN"
    ],
    "layout": "bullets"
  },
  {
    "id": 6,
    "title": "PCB Layout",
    "intro": null,
    "bullets": [
      "Schematic Entry",
      "Thermal Analysis",
      "Ansys ICEPACK",
      "Altium Designer, Allegro X Design , Eagle Autodesk, Kicad.",
      "Altium Designer, Allegro X Design , Eagle Autodesk, Kicad.",
      "CAM",
      "CAM350 / UCAM",
      "PACKAGE DESIGN",
      "Allegro  ADP",
      "Signal Integrity / Power Integrity",
      "Keysight ADS PathWave, HFSS",
      "TOOLS EXPERTISE"
    ],
    "layout": "bullets"
  },
  {
    "id": 7,
    "title": "Senanitech delivers end-to-end Reliability and Burn-In solutions, offering expert BIB design that maximizes test coverage at minimum cost. Our experienced team handles CAF, tight pitch, high power, de-rating, and custom circuitry needs — making us a trusted partner for semiconductor reliability challenges.",
    "intro": null,
    "bullets": [
      "BURN-IN-BOARDS",
      "Types of Boards:",
      "Burn-in Boards for All Systems (Including High-Power BIB’s)",
      "HAST Boards",
      "HTOL- Infinity i160/ Infinity i8160/ Tahoe",
      "Test Fixtures for Failure Analysis",
      "THB (Temperature-Humidity-Bias)",
      "Special Application Boards"
    ],
    "layout": "bullets"
  },
  {
    "id": 8,
    "title": "Hast Board",
    "intro": null,
    "bullets": [
      "Up to 10-Layer Stack up: Uses Polyimide",
      "30-Cell Optimized 30-DUT matrix placement to ensure 100% uniform.",
      "Dog-Bone Via Fan-out: Precision dog-bone escape routing to prevent solder wicking",
      "HAST Leakage Control: Strict 15–20 mil isolation spacing",
      "Develop a customized socket footprint."
    ],
    "layout": "bullets"
  },
  {
    "id": 9,
    "title": "Hast Board",
    "layout": "tech",
    "columns": [
      {
        "title": "Package Detail",
        "items": [
          "Up to 1156-pin BGA",
          "Ultra-High Density",
          "Fine-Pitch."
        ]
      },
      {
        "title": "Power Design",
        "items": [
          "Up to 20+ Independent Rails",
          "High-Current Plane Segmentation."
        ]
      },
      {
        "title": "Routing",
        "items": [
          "Phase-Matched Differential Pairs",
          "Within-Group Length Tuning."
        ]
      },
      {
        "title": "Fan-out",
        "items": [
          "100% Net Accessibility",
          "Full Diagnostic Fault Isolation (FI)."
        ]
      },
      {
        "title": "Stack up",
        "items": [
          "Up to 22-Layer Ultra-Dense Architecture",
          "Advanced Impedance Control."
        ]
      }
    ]
  },
  {
    "id": 10,
    "title": "Infinity i160 & i8160 HTOL Platforms",
    "layout": "tech",
    "columns": [
      {
        "title": "Package Detail",
        "items": [
          "84 PDQFN",
          "30-Cell High-Density BIB Matrix."
        ]
      },
      {
        "title": "Power Design",
        "items": [
          "i160 (4-Rail)",
          "i8160 (8-Rail)",
          "Integrated Per- Dut Power Monitoring."
        ]
      },
      {
        "title": "Routing Strategy",
        "items": [
          "Precision Per-Row & Per-BIB isolation with Kelvin Sensing for voltage accuracy."
        ]
      },
      {
        "title": "Fan-out Tech",
        "items": [
          "Dedicated Dog-Bone escape to maintain heat stress."
        ]
      },
      {
        "title": "Critical Layering",
        "items": [
          "8-Layer Ultra-Dense Stack up",
          "Balanced copper distribution to prevent thermal warping."
        ]
      }
    ]
  },
  {
    "id": 11,
    "title": "Tahoe High-Performance HTOL",
    "layout": "tech",
    "columns": [
      {
        "title": "Package Detail",
        "items": [
          "LFG1156 (1156-Pin)",
          "400K Logic Gate Density",
          "9-DUT (9-Socket) Matrix."
        ]
      },
      {
        "title": "Power Design",
        "items": [
          "Ultra-High Current Distribution",
          "Per- Dut Power Monitoring",
          "Multi-Phase Voltage Rails."
        ]
      },
      {
        "title": "Fan-out Tech",
        "items": [
          "High-Density Dog-Bone escape for 1.0mm pitch; designed for zero mechanical interference with socket hardware."
        ]
      },
      {
        "title": "Critical Layering",
        "items": [
          "22-Layer Ultra-Dense Stack up",
          "Massive Copper planes for high-current thermal heat-sinking."
        ]
      }
    ]
  },
  {
    "id": 12,
    "title": "ESD Board",
    "layout": "tech",
    "columns": [
      {
        "title": "Package Detail",
        "items": [
          "Up to 1156-pin BGA",
          "Ultra-High Density",
          "Fine-Pitch."
        ]
      },
      {
        "title": "Power Design",
        "items": [
          "Up to 10+ Independent Rails",
          "High-Current Plane Segmentation."
        ]
      },
      {
        "title": "Routing",
        "items": [
          "All the signals trace are having the same propagation delays"
        ]
      },
      {
        "title": "Fan-out",
        "items": [
          "100% Net Accessibility",
          "Full Diagnostic Fault Isolation (FI)."
        ]
      },
      {
        "title": "Stack up",
        "items": [
          "Up to 12-Layer Ultra-Dense Architecture",
          "Advanced Impedance Control."
        ]
      }
    ]
  },
  {
    "id": 13,
    "title": "Industrial Automation Relay Board",
    "intro": null,
    "bullets": [
      "Master Relay Board",
      "12 layers / 4597 Pins",
      "High Current",
      "Ultrahigh density",
      "Altium Designer",
      "Chipset - C2000"
    ],
    "layout": "bullets"
  },
  {
    "id": 14,
    "title": "AGX Motherboard",
    "intro": null,
    "bullets": [
      "Commercial Application",
      "16 layer",
      "HighSpeedDigital",
      "FPGA / nVidia Motherboard",
      "High-Speed Display Output",
      "8326 pins",
      "Frequency 2.2GHz"
    ],
    "layout": "bullets"
  },
  {
    "id": 15,
    "title": "Rugged SBC Board",
    "intro": null,
    "bullets": [
      "Ultra-high density",
      "MilitaryApplication",
      "14 layer",
      "HighSpeedDigital",
      "HDI–Blind/Buried Sets",
      "FPGA/LPDDR",
      "12 Layer"
    ],
    "layout": "bullets"
  },
  {
    "id": 16,
    "title": "FPGA Processor Board",
    "intro": null,
    "bullets": [
      "FPGA ProcessingHardware",
      "Highspeeddigital/HDMI/FPGA",
      "Altium Designer 21",
      "High Current",
      "Digital PowerTrain",
      "Total pincount:9360",
      "Impedance Requirement",
      "4xDDR3L",
      "10 Layer"
    ],
    "layout": "bullets"
  },
  {
    "id": 17,
    "title": "RIGID - FLEX PCBS",
    "intro": null,
    "bullets": [
      "Low density, Medical grade wireless.",
      "Wireless BLE Application",
      "6 layer",
      "RF Based",
      "High-Volume product",
      "BLE-5"
    ],
    "layout": "bullets"
  },
  {
    "id": 18,
    "title": "PMU Device",
    "intro": null,
    "bullets": [
      "High density",
      "High Current Board",
      "18 layers",
      "Parametric measurement unit (PMU)",
      "6532 pins"
    ],
    "layout": "bullets"
  },
  {
    "id": 19,
    "title": "High Power Board - Traction Control",
    "intro": null,
    "bullets": [
      "HV Board",
      "4 layers",
      "120A",
      "570mm X 370mm",
      "Automotive"
    ],
    "layout": "bullets"
  },
  {
    "id": 20,
    "title": "Aerospace PCBs",
    "intro": null,
    "bullets": [
      "HighDensity–RF Design",
      "HighLayercount–8-14 layers",
      "ImpedanceControlled"
    ],
    "layout": "bullets"
  },
  {
    "id": 21,
    "title": "iMX6 Processor",
    "intro": null,
    "bullets": [
      "HighDensity–0.4mmBGA",
      "High Layercount–12 layers",
      "Impedance Controlled",
      "Dual DDR3"
    ],
    "layout": "bullets"
  },
  {
    "id": 22,
    "title": "Industrial Control Card",
    "intro": null,
    "bullets": [
      "HighDensity Board",
      "HighLayercount–14  layers",
      "Impedance Controlled",
      "Controller Based"
    ],
    "layout": "bullets"
  },
  {
    "id": 23,
    "title": "Medical Electronics PCBs",
    "intro": null,
    "bullets": [],
    "layout": "bullets"
  },
  {
    "id": 24,
    "title": "Automobile PCBs",
    "intro": null,
    "bullets": [
      "ST"
    ],
    "layout": "bullets"
  },
  {
    "id": 25,
    "title": "ELECTRONICS MANUFACTURING SERVICES",
    "intro": null,
    "bullets": [],
    "layout": "bullets"
  },
  {
    "id": 26,
    "title": "KEY FEATURES IN SOLDER PASTE PRINTER (MODEL : DEK 03I)",
    "intro": null,
    "bullets": [
      "Cycle time: 12 Sec (Excluding printing time)",
      "Applicable stencil size: L736mm x L736mm.",
      "Graphical Layer Base alignment function",
      "Stencil Vacuum Function: A stencil vacuum  mechanism delivers consistent high accuracy printing with no effects from stencil drops.",
      "ASM Adjustable Stencil Mount",
      "PCB Size: L580x W508mm.",
      "Squeegee Pressure Mechanism: Software-controlled, motorised"
    ],
    "layout": "bullets"
  },
  {
    "id": 27,
    "title": "Key Features in Pick and Place (Model : YSM10)",
    "intro": null,
    "bullets": [
      "Fixed plate: Max. 96 types (conversion for 8 mm tape feeder) Tray: 15 types (maximum when equipped with sATS 15, JEDEC)",
      "Rated Speed: HM head (10 nozzle) specification : 46,000CPH , HM 5 head (5 nozzle) specification : 31,000CPH",
      "PCB Size : L 510 x W 460mm",
      "Accuracy: +/-0.035mm (+/-0.025mm)",
      "Component range : 03015mm to Board W55 x L100mm",
      "Improves scan camera performance that expands the size of high-speed mounting parts to 12mm.Supports ball recognition such for BGA and CSP, etc."
    ],
    "layout": "bullets"
  },
  {
    "id": 28,
    "title": "Key features in Reflow  oven (Model: KONARK 710S )",
    "intro": null,
    "bullets": [
      "MAXIMUM PCB WIDTH OF 400 MM",
      "14 INDEPENDENTLY PID CONTROLLED HEATING ZONES",
      "MAX TEMP : 360°C",
      "LEADFREE CAPABLE",
      "REPEATABILITY: - +/- 1°C",
      "Mass Production: +/- 2°C"
    ],
    "layout": "bullets"
  },
  {
    "id": 29,
    "title": "WHY choose us",
    "intro": "High-Quality PCB Design, Clean Documentation, Guaranteed Lower Prices Our team delivers exceptional PCB designs with thorough documentation, all at a guaranteed competitive price. Our highly skilled PCB designers deliver precise, reliable, and efficient designs, ensuring top quality and performance for every project. Well-organized schematic symbols, PCB footprints, and 3D models for efficient design integration. Ensuring accuracy and consistency throughout the entire process. We maintain a clean communication model, providing daily status reports and facilitating online design reviews for seamless collaboration. Our team provides round-the-clock support to ensure your design timeline is fully accommodated and compensated. We offer competitive discounts for clients engaging in long-term collaborations.",
    "bullets": [
      "Skilled Engineers",
      "Documentation",
      "Organize",
      "Proper Communication - Daily Status Report",
      "24/6 Comprehensive Support",
      "Discounted Rates for Long-Term Partnerships"
    ],
    "layout": "bullets"
  },
  {
    "id": 30,
    "title": "VALUE ADDED SERVICES",
    "intro": "We provide comprehensive PCB assembly services, ensuring high-quality production and efficient turnaround times for all your electronic projects. Our box building and power-on testing services ensure your assembled PCBs are securely packaged and fully functional, providing reliable performance right out of the box. PatternPCB has established long-term relationships with suppliers in the USA, Taiwan, China, and India. We can help you select the right supplier to meet your specific needs.",
    "bullets": [
      "2–80Layer / IPCClass2 and Class3 / HDI (2-n-2), (3-n-3)/ Flex/ Rigid - Flex",
      "Component Sourcing",
      "PCB Fabrication",
      "PCB Assembling / SMT/X-Ray/MicroBGA",
      "Box Building and Power-On Testing Services",
      "Strong Supplier Partnerships Across the Globe"
    ],
    "layout": "bullets"
  },
  {
    "id": 31,
    "title": "VALUABLE CLIENTS",
    "subtitle": "",
    "layout": "title"
  },
  {
    "id": 32,
    "title": "ENGINEERING DELIVERY CENTRE",
    "intro": "INFITECH ELECTRONICS NO:15 CORPORATION ROAD SEEVARAM PERUNGUDI CHENNAI -600096",
    "bullets": [
      "2ND FLOOR, SRI VALLIAPPA BLOCK,SONA INCUBATION FOUNDATION, JUNCTION MAIN ROAD",
      "SALEM - 636005, TAMIL NADU, INDIA",
      "Thank",
      "you!",
      "SENANITECH - MANUFACTURING"
    ],
    "layout": "bullets"
  }
];
